version: '3.8'

services:
  orquestador:
    image: orquestador:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - .:/app